# Generated by Django 4.0.4 on 2022-05-29 07:35

import base_lib.model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_developer_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.UUIDField(default=base_lib.model.create_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveSmallIntegerField()),
                ('content', models.TextField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='account.developer')),
            ],
            options={
                'unique_together': {('developer', 'title')},
            },
        ),
        migrations.CreateModel(
            name='FamiliarGigQuestion',
            fields=[
                ('id', models.UUIDField(default=base_lib.model.create_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gig.gig')),
            ],
            options={
                'unique_together': {('gig', 'question')},
            },
        ),
    ]
