# Generated by Django 4.0.4 on 2022-05-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='files',
            field=models.FileField(null=True, upload_to='proposal/docs'),
        ),
    ]
