# Generated by Django 4.0.4 on 2022-05-29 07:23

import base_lib.model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_developer_client'),
        ('job', '0003_proposal_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRating',
            fields=[
                ('id', models.UUIDField(default=base_lib.model.create_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client_rating', models.PositiveSmallIntegerField(null=True)),
                ('client_message', models.TextField(null=True)),
                ('client_rating_posted', models.DateTimeField(null=True)),
                ('developer_rating', models.PositiveSmallIntegerField(null=True)),
                ('developer_message', models.TextField(null=True)),
                ('developer_rating_posted', models.DateTimeField(null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='job.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobInvite',
            fields=[
                ('id', models.UUIDField(default=base_lib.model.create_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='got_invited', to='account.developer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='job.job')),
            ],
            options={
                'unique_together': {('job', 'developer')},
            },
        ),
    ]
